# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(690, 40, 81, 31))
        self.submit.setObjectName("submit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 91, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.file_path = QtWidgets.QLineEdit(self.centralwidget)
        self.file_path.setEnabled(False)
        self.file_path.setGeometry(QtCore.QRect(120, 40, 461, 31))
        self.file_path.setText("")
        self.file_path.setObjectName("file_path")
        self.browse_file = QtWidgets.QPushButton(self.centralwidget)
        self.browse_file.setGeometry(QtCore.QRect(590, 40, 91, 31))
        self.browse_file.setObjectName("browse_file")
        self.result_list = QtWidgets.QTableView(self.centralwidget)
        self.result_list.setEnabled(True)
        self.result_list.setGeometry(QtCore.QRect(30, 90, 741, 421))
        self.result_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.result_list.setDragDropOverwriteMode(False)
        self.result_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.result_list.setGridStyle(QtCore.Qt.SolidLine)
        self.result_list.setObjectName("result_list")
        self.result_list.horizontalHeader().setCascadingSectionResizes(False)
        self.result_list.verticalHeader().setVisible(False)
        self.result_list.verticalHeader().setCascadingSectionResizes(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DRML"))
        self.submit.setText(_translate("MainWindow", "确定"))
        self.label_3.setText(_translate("MainWindow", "数据文件"))
        self.browse_file.setText(_translate("MainWindow", "浏览文件"))
