# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(730, 40, 221, 81))
        self.submit.setObjectName("submit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 91, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.file_path = QtWidgets.QLineEdit(self.centralwidget)
        self.file_path.setEnabled(False)
        self.file_path.setGeometry(QtCore.QRect(120, 40, 461, 31))
        self.file_path.setText("")
        self.file_path.setObjectName("file_path")
        self.browse_file = QtWidgets.QPushButton(self.centralwidget)
        self.browse_file.setGeometry(QtCore.QRect(610, 40, 91, 31))
        self.browse_file.setObjectName("browse_file")
        self.result_list = QtWidgets.QTableView(self.centralwidget)
        self.result_list.setEnabled(True)
        self.result_list.setGeometry(QtCore.QRect(40, 130, 921, 441))
        self.result_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.result_list.setDragDropOverwriteMode(False)
        self.result_list.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.result_list.setGridStyle(QtCore.Qt.SolidLine)
        self.result_list.setObjectName("result_list")
        self.result_list.horizontalHeader().setCascadingSectionResizes(False)
        self.result_list.verticalHeader().setVisible(False)
        self.result_list.verticalHeader().setCascadingSectionResizes(False)
        self.minpts = QtWidgets.QSpinBox(self.centralwidget)
        self.minpts.setGeometry(QtCore.QRect(390, 90, 81, 31))
        self.minpts.setProperty("value", 2)
        self.minpts.setObjectName("minpts")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 90, 91, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 90, 101, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(500, 90, 101, 31))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.cluster = QtWidgets.QSpinBox(self.centralwidget)
        self.cluster.setGeometry(QtCore.QRect(620, 90, 81, 31))
        self.cluster.setProperty("value", 3)
        self.cluster.setObjectName("cluster")
        self.eps = QtWidgets.QSpinBox(self.centralwidget)
        self.eps.setGeometry(QtCore.QRect(160, 90, 81, 31))
        self.eps.setProperty("value", 3)
        self.eps.setObjectName("eps")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DRML"))
        self.submit.setText(_translate("MainWindow", "确定"))
        self.label_3.setText(_translate("MainWindow", "数据文件"))
        self.browse_file.setText(_translate("MainWindow", "浏览文件"))
        self.label_4.setText(_translate("MainWindow", "DBSACN eps"))
        self.label_5.setText(_translate("MainWindow", "DBSACN minPts"))
        self.label_6.setText(_translate("MainWindow", "Kmeans Cluster"))
