# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualize.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Visualize(object):
    def setupUi(self, Visualize):
        Visualize.setObjectName("Visualize")
        Visualize.resize(1000, 800)

        self.retranslateUi(Visualize)
        QtCore.QMetaObject.connectSlotsByName(Visualize)

    def retranslateUi(self, Visualize):
        _translate = QtCore.QCoreApplication.translate
        Visualize.setWindowTitle(_translate("Visualize", "可视化"))
